- SoundBars/Soundblasterx.ir
- TVs/Sonyxbr_RMT_TX200U.ir
The current Sony XBR remote file is specific to an unknown Sony XBR remote. The TX200U remote has different buttons and options (Power versus On/Off) that use different commands
> Add Sony XBR RMT-TX200U and SoundblasterX remotes

- ACs/Koldfront_wac12001.ir
- ETC/Jet_AFS-1000b.ir
Here are two remotes captured via Flipper. One is for a Jet AFS-1000B air filtration system, typically used to clean dust and particles in a workshop. The other is for a Koldfront window AC unit, model WAC12001.
> Add two random IR captures

- ACs/LG/LP1015WNR.ir
Self-explanatory, had to go dig up a remote bc literally nowhere has this model's code online, although it'll probably work for multiple models.
> LG Portable AC LP1015WNR added

- Audio_Receivers/Yamaha/Yamaha_RAS5.ir
Hi, we met at the Discord, I am adding a remote for Yamaha audio amp/receiver RAS5, it comes with A-S500, but should be compatible with many others, since it has receiver and tuner buttons.
> Added Yamaha RAS5 compatible with A-S500 and others.

- ACs/Remko/Remko_RKL.ir
I tested this with a Remko RKL 360 S-Line.
The replacement IR remote had the other series listed as well, so it's the same for those models as well.
I hope the naming is fine.
> Add Remko RKL 360/460/470/480 Series AC Remote.

- Audio_Receivers/CambridgeAudio/CambridgeAudio_650A.ir
- Miscellaneous/Gakken/Gakken_WorldEye.ir
Add Cambridge Audio 650A under audio receivers.
Add Gakken Worldeye under miscellaenous.
> Cambridge Audio 650A Receiver & Gakken Worldeye

- Audio_Receivers/Yamaha/YAMAHA_AX-380.ir
The process of getting these was a bit convoluted to say the least.
Because I don't have a remote for the device, I had to rely on the information provided by the lirc project:
https://lirc.sourceforge.net/remotes/yamaha/VR50590
However, those codes were not flipper compatible, so to get those onto the flipper, I've used an ESP8266-based WiFi IR Blaster flashed with the Tasmota firmware to send those keycodes found in the lirc config (excluding the 0x00000000 prefix) and then let the Flipper decode that Signal.
There must be a less hacky solution to convert between these two formats but it worked decently for those nine keycodes.
> Add Yamaha AX-380 Stereo Amplifier

- Streaming_Devices/Roku/Roku2.ir
- Streaming_Devices/Roku/Roku2_channels.ir
Adds IR file to directly access channels from the Roku2 devices.
As there are numerous channels, and most users probably won't want all of them, I've added the channel buttons as a separate file, to make it easier for users to pick and choose any channels they want.
> Add Roku2 channels

- Miscellaneous/GX-IR03.ir
- Miscellaneous/Gym_HIIT/GX-IR03_Clock.ir
This is the full IR profile for the GX-IR03 remote that controls most AliExpress, Amazon, and other off-brand Gym/HIIT clocks.
Known to work with [this clock from AliExpress](https://www.aliexpress.us/item/2255799914300348.html) but will most likely work with most Interval Training clock
> Add GX-IR03 Gym/HIIT Clock remote

- Speakers/Microlab/Microlab_RC071.ir
Similar remote control in [this repo converted folder](https://github.com/Lucaslhm/Flipper-IRDB/blob/main/_Converted_/IR_Plus/M/MICROLAB/Speakers.ir) has similar codes, but in LSB first representation and encoding is NECext - that didn't work for me and I couldn't figure out how to fix it.
I grabbed the signal with a Flipper Zero from my [Arduino-based emulator](https://github.com/Alex-Tsarik/Arduino-IR-RC-Microlab-SOLO) (which works with speakers), and after understanding the conversion, added all the buttons. Tested with speakers Microlab SOLO 5c.
> Create  Microlab_RC071.ir

- Miscellaneous/WayneDresser/WayneDresser_GasPump_Remote.ir
This ir file is all of the buttons on a gas pump technicians programming remote for a Wayne Dresser (Brand) gas pump. (Works with several models)
- a pass code is required to change programming, there is a default pass code.
- the "remote" function of the gas pumps can be disabled internally by a technician, so wont work on all of them unless they forgot to disable it.(happens a lot)
I am new to github and wanted to contribute something i think would be cool. I read these codes from my own remote.
> Gas Pump Programming Remote for Wayne Dresser Pumps

- Projectors/Coolux/Coolux_X3S.ir
It uses NEC codes at address `0x1`.
> Add code for Coolux X3S projector

- Audio_Receivers/Sony/Sony_RMT-AA400U.ir
The Remote Control is compatible with [Sony STR-DH190 Stereo Receiver](https://www.sony.com/electronics/av-receivers/str-dh190).
> Add Sony RMT-AA400U Remote Control

- SoundBars/JBL/JBL_5_1_Soundbar.ir
- Added a Bass- button
- Renamed Bass to Bass+
- Moved Bass+ and Bass- to the bottom as a more logical grouping
> Revised the JBL Soundbar 5.1

- Audio_Receivers/NAD/NAD_Amp_1.ir
- Audio_Receivers/NAD_Amp_1.ir
Add a basic remote used with several NAD audio products.
> Add NAD AMP 1 remote, included with NAD C 315BEE and many others.

- VCR/Panasonic/Panasonic_Light_Tower_LSSQ0342.ir
seems to be a common Model Panasonic Omnivision VCR, didn't see the Remote in the DB.  only 4 buttons not recorded/not Possible, "VCR" "TV" "SAT/Cable" modes & "Add/DLT" (this recorded by flipper, but did nothing on Playback.) Remote Functions as a Universal Remote as well however seems to be Secondary function as very spare set of supported Models TVs Cable boxes/satellite receivers in it's Manual.
> Add Panasonic Light Tower LSSQ0342

- Audio_Receivers/SMSL/SMSL_RC-8A.ir
This works for SMSL bluetooth amplifier model AO100 and any other models using the same RC-8A remote.
> Add SMSL RC-8A

- .gitignore
- LED_Lighting/Jialine_Candle/10-key_Candle.ir
Added file for flickering flameless LED candles that use a 10-key remote, and are available under several brand names such as Angelloong, Homemory, and Jialine.
- Power on/off
- Timer 2/4/6/8 hr
- Flicker/steady
- Bright/dim
> Added file for Jialine 10-key LED candle remote

- Converters/RetroTINK/RetroTINK_4K.ir
- Converters/RetroTINK/RetroTINK_5X_Prem.ir
- Converters/RetroTINK/RetroTINK_5X_Std.ir
Adding RetroTINK 5X and 4K remotes, these devices are "converters" similar to the OSSC.
> Adding RetroTINK 5X and 4K remotes

- Multimedia/DuneHD/DuneHD.ir
Add DuneHD Remote Control
Compatible with the players:
Kartina X
Kartina S
Kartina Micro HD
Kartina Relax
Dune HD Max
Dune HD Duo
Dune HD Base 3D
Dune HD TV-101
Dune HD TV-102
Dune HD TV-301
Dune HD TV-303D
Dune HD Connect
Dune HD Smart B1
Dune HD Smart H1
Dune HD Smart D1
Dune HD Lite 53D
Dune BD Prime 3.0
Dune BD Prime
Dune HD Base 3.0
Dune HD Base 2.0
Dune HD Base
Captured from the original remote
> Add DuneHD remote control

- Fans/Shark/Shark_FlexBreeze-FA22X.ir
I captured the codes from a  FA220UK, im assuming the remotes are the same internationally, so i have tentatively named the file `Shark_FlexBreeze-FA22X.ir` as the main diffrence between the UK, EU, and US version are the last digit(220 seems to be the European model, and 222 the US) and the last 2 letters being the plug type(UK, EU, the US one drops the letters)
> Fan - Add Shark Flex Breeze

- LED_Lighting/Lethe/Lethe_RGB_LED_full.ir
Added the full mapping of the Lethe RGB LED Strip Remote (the one in the  repository has mappings only for On and Off buttons as of now).
> Added Lethe RGB LED Strip (full)

- SoundBars/Philips/Philips_TAB5105_79.ir
- TVs/Philips/Philips_50PUT6103_79.ir
These codes learned from Philips remote
control model no 398GR08BEPHN0025JH packaged
with TV model 50PUT6103/79
Codes read by Flipper Zero
-=-=-
These codes learned from remote for
Philips soundbar model TAB5105/79
Codes read from remote with Flipper zero
> Philips TV and Soundbar

- Monitors/Monoprice/Monoprice_43305.ir
Learned IR Codes for Dark Matter by Monoprice 49in Curved Gaming Monitor Model No. 43305.
Created new Monoprice folder under Monitors and added Monoprice_43305 IR file.
Note: This monitor model initially included a dedicated remote but was removed and never sold seperately.
> Created Monitors/Monoprice and added Monoprice 43305 IR file

- TVs/TCL/TCL_65C635K.ir
Added an additional TV remote for the TCL 65C635K.
All button included sorted by common usage/convenience.
> Added TCL 65C635K TV Remote

- Multimedia/Rytaki/Rytaki_US_HDMI501-8K-H.ir
This adds captured/parsed signals for the Rytaki US HDMI501-8K-H powered HDMI 5x1 switch (e.g. https://www.amazon.com/dp/B0CC4LGH2C).
> Added Rytaki US HDMI501-8K-H HDMI Switch

- TVs/LG/LG_AKB75375608.ir
LG AKB75375608 Remote Control
fit for a multitude of different models (listed in the commit)
> LG_AKB75375608

- TVs/Gogen/Gogen_TVH24P266T.ir
New TV added.
- TVs/Gogen/Gogen_TVH24P266T.ir : Added a new file with IR signal data for TV Gogen TVH24P266T.
> Added Gogen TVH24P266T

- TVs/LG/LG_MKJ33981404.ir
Also fits to the following models:
- LG 21FG5RL
- LG 21FJ8RL
- LG 21FK2RG
- LG 21FU4R-L3
- LG 21FU4RL
- LG 21FU4RLX
- LG 21FU6-L4
- LG 21FU6PL
- LG 21FU6R-L4
- LG 21FU6RG
- LG 21FU6RL
- LG 21FU6RL-Z4
- LG 21FU6RLX
- LG 21FU6T
- LG 21FU6TL
- LG 21SA1RL
- LG 21SB1RL
- LG 21SB1RG-Z4
Product page:
https://pulthouse.com.ua/pulty-du-televizor/lg-mkj33981404/
> Remote for  LG MKJ33981404

- Audio_and_Video_Receivers/MCM_Custom_Audio/MCM_Volume_Control_50-8394.ir
This adds support for the MCM Custom Audio Volume Control, available from https://www.newark.com/mcm-custom-audio/50-8394/line-level-volume-control-rohs/dp/79X4195. The only control on the remote are mute, volume up and volume down.
Note: the datasheet on that page claims to have the IR codes, but they don't work, and the ones in this PR are taken from the flipper learning a working remote.
> Add MCM Custom Audio Volume Control

- Miscellaneous/RocketFish/RF_G1501.ir
Manual: https://files.bbystatic.com/4G8hdhTB%2F56AOz0EqiDKhw%3D%3D/RF-G1501_RF-G1501-C_20-0446_QSG_V8_EN_Final_lr.pdf
Input source buttons don't follow the naming scheme due to it not being listed in that scheme
> Add rocketfish hdmi switch RF-G1501

- Touchscreen_Displays/Legamaster/Legamaster_DIS-9800.ir
This remote file is for the Touchscreen Display Legamaster DIS-9800 or Legamaster Discover-9800. I don't know if it is also compatible with the next version (Discover-2 or DIS-9810), but I assume it should also work with that one.
> Adding Legamaster_DIS-9800 file to Touchscreen Displays

- Projectors/Epson/Epson_EBX7_154720000.ir
The numpad keys are named from 0 to 9 and then Num0 to Num9, some of those keys weren't sending a code while being pressed but did/sent a different code than the key alone when Num was pressed along with the key. So 0 to 9 means the key alone and Num0 to Num9 means Num+Key.
> Add Epson EBX7 Remote - Epson Controller 154720000

- .fff-ir-lint.json
- The AVR path had a typo, meaning it wasn't being checked
- A number of other similarly-behaving paths didn't have lints, this added those directories
> Add additional paths to linter

- VCR/Sony/Sony_SLV-D281P.ir
- VCR/Sony/Sony_slvd281p.ir
most buttons for the SLV-D281P DVD/VCR combo unit, didnt get every button on the remote as most are useless for just watching DVDs, VHS Tapes, and using the 2 composite inputs on the unit
> most buttons for the SLV-D281P DVD/VCR combo unit
