Lucaslhm/Flipper-IRDB

- Cameras/Nikon.ir
Adding following remote which works with loads of Nikon cameras. 
https://www.amazon.com/AmazonBasics-Wireless-Control-Shutter-Release/dp/B003L1ZYZ6
> Adding Nikon Camera Remote

- LED Lighting/mlambert_rope_light.ir
https://www.amazon.com/gp/product/B07RBQ2KHH/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
All functions on the remote control (2021 model) scanned and tested.
> Mlambert rope lights

- Audio Receivers/Rega/Rega_IO.ir
Adding Rega_IO receiver IR codes
> Adding Rega_IO receiver remote

- Consoles/Microsoft/Xbox.ir
Adds back button to Xbox remote
> Add back button to Xbox remote

- Speakers/creative/z5400.ir
Full remote control for Creative Z5400
> Add support for Creative Z5400

- TVs/Element/Element_100-Series_TV.ir
Add IR codes for Element Standard TV remote
> Add Element 100 Series TV

- TVs/ContinentalEdison/ContinentalEdison_CELED502723.ir
Added remote button for Continental Edison CELED502723.
All buttons added.
> Remote for Continental Edison CELED502723

- LED_Lighting/Feron/Feron_AL5000_Starlight.ir
- TVs/Sceptre/Sceptre_X50_Series.ir
- Sceptre TV
- Feron AL5000 light
> Few more to add

- TVs/LG/LG_MKJ39170828_Service.ir
LG MKJ39170828 service remote for getting into settings on LG TVs.
> Added LG MKJ39170828 service remote

- TVs/Blitzwolf/Blitzwolf_BWPCM2.ir
It is a portable HDMI/USB-C monitor with IR remote, I've placed it in the TV folder.
> Blitzwolf_BWPCM2

- TVs/Philips/Philips_TV_14PV172_08.ir
To be able to change between HDMI1, HDMI2, etc.
> Add SOURCE button to remote

- Audio_Receivers/SMSL/SMSL_RC-8C.ir
Add SMSL RC-8C remote for the SMSL M500 MKII
> Add SMSL_RC-8C.ir

- Miscellaneous/GANXIN/GANXIN_GXIR05.ir
> Add GX-IR05 Remote for GAN XIN Training Clock

- CD_Players/Aiwa/AIWA_NSXR71.ir
> Add Aiwa NSX-R71 CD Player

- Heaters/Devola/Devola_ DVPH1200B _Patio_Heater.ir
Add a common UK patio heater often found in beer gardens.
> Create Devola_ DVPH1200B _Patio_Heater.ir

- TVs/Panasonic/Panasonic_TX_42AS650E.ir
> Add Panasonic TX-42AS650E remote

- SoundBars/Canton/Canton_Smart10.ir
Remote for the Smart Soundbar 10 from Canton (may work with other Canton Soundbar as well).
> Add Canton Remote

- Universal_TV_Remotes/BenQ/BenQ remote control | TRY01.ir
- Universal_TV_Remotes/BenQ/BenQ_TRY01.ir
https://www.benq.com/en-us/business/ifp/try01.html
The other buttons are seemly controlled via Bluetooth?
> Create BenQ remote control | TRY01.ir

- TVs/Samsung/Samsung.ir
I added some "important" buttons (0-9 and CH+ & CH-) 
In addition, I have made the order a bit more better.
> Buttons added, order improved/changed

- Whiteboards/Promethan/Promethan_ActivPanel.ir
> New whiteboard: Promethean_ActivPanel.ir

- Vacuum_Cleaners/iCLEBO/iCLEBO_Omega.ir
I think it's a good idea to create a new category for the vacuum cleaners.
> Added iCLEBO Omega vacuum cleaner robot.

- Speakers/Logitech/Z906.ir
Note there is already a converted file at `_Converted_/IR_Plus/L/LOGITECH/Z906.ir` but it appears to not work.
> Add Logitech Z906

- Speakers/Edifier/Edifier_RC17A.ir
Added IR Signals file for the Edifier RC17A remote. Tested all signals with the R1700BT speakers.
> Speakers: Edifier: Add IR signals for the Edifier RC17A remote

- TVs/Samsung/Samsung-Service-Menu.ir
- TVs/Samsung/Samsung_Service_Menu.ir
Add Samsung Service Menu. Turn off the Device and send the commands one after the other to open hidden service menu. 1.Info 2.Menu 3.MUTE 4.POWER
> Add Samsung Service Menu. 

- Projectors/Optoma/Optoma_DH1011.ir
Created using factory remote and Flipper Zero
> Optoma DH1011 DLP

- Cable_Boxes/Huawei/Huawei_dn300_mgts(mts).ir
added Huawei_dn300_mgts(mts) remote controler https://cache3.youla.io/files/images/720_720_out/5c/5f/5c5f2a2eaaab2862d173cbef.jpg
> added Huawei_dn300_mgts(mts) remote controler

- TVs/LG/AKB75375604.ir
- TVs/LG/LG_TV_AKB75375604.ir
> AKB75375604

- Audio_Receivers/Sony/Sony_RMT-AA320U_AV.ir
- Blu-Ray/Oppo/OPPO_BDP93.ir
- TVs/Fetch/Fetch_TV_Box_AUS.ir
- TVs/Sony/Sony_RM-GD014.ir
- Addition of Sony RMT-AA320U_AV
- Addition of OPPO_BDP93
- More buttons added to Fetch_TV_Box_AUS
- Addition of Sony RM-GD014
> New Remotes

- Touchscreen_Displays/ViewSonic/ViewBoard.ir
- Touchscreen_Displays/ViewSonic/ViewSonic_ViewBoard.ir
> ViewSonic ViewBoard IR File

- Vacuum_Cleaners/Samsung/Samsung_SC18M31A0HU.ir
> Added Samsung SC18M31A0HU

- Speakers/KEF/KEF_LSX_Speakers.ir
- Speakers/KEF/LSX.ir
https://assets.kef.com/pdf_doc/LSX/LSX-manual-EN.pdf 
section 5.3 about remote
> Added KEF LSX Speakers

- Vacuum_Cleaners/Samsung/Samsung_SR8875
Samsung SR8875 Vacuum Robot working ir codes 
Captured with the Flip0
> Create Samsung SR8875 Vacuum Robot IR codes

- Projectors/BenQ/BenQ_TH671ST.ir
Adding another BenQ projector.
IR file created with Flipper Zero.
Button names updated to fit repo style.
> Add BenQ TH671ST

- Touchscreen_Displays/Newline/Newline_Interactive_Board.ir
Added `Touchscreen_Dsiplay/Newline/Newline_Interactive_Board.ir`
For both education and Q-series boards
> New remote: Newline Interactive board

- Videoconferencing/Bose/Videobar.ir
Three of the buttons couldn't get parsed beyond raw, unfortunately!
> Remote for Bose Videobar

- LED_Lighting/iDual/iDual.ir
Was previously partly in German
> Translation to English

- TVs/Hotels/Marriott-BONVoY_Remote.ir
-Added a Hotels directory under TVs to collect remotes from hotel chains. 
-Added a remote for Marriott's BONVoY chain. | Marriott-BONVoY_Remote.ir
> Added TVs/Hotels Dir | Marriott Remote

- SoundBars/Yamaha/Yamaha_YAS-CU201.ir
IR file for the Yamaha soundbar model YAS-CU201.
> Yamaha_YAS-CU201.ir

- Audio_Receivers/Edifier/Edifier_r1280t.ir
Added RC10 remote for Edifier R1280T
> Edifier R1280T

- ACs/Princess/Princess_AC.ir
- ACs/Princess/Princess_ac.ir
Adds support for Princess Air Conditioner, product page: https://www.amazon.co.uk/dp/B07NFMD51D
> Added Princess Air Conditioner

- TVs/TCL/TCL_Roku_TV.ir
Adds Amazon Prime and Youtube buttons
> Add channel buttons to TCL_Roku_TV.ir

- Cameras/Eakins/Eakins_48MP.ir
A Chinese microscope camera, sampled from remote that came with the set.
> Added Eakins 48MP FullHD microscope camera

- Whiteboards/Promethean/Promethean_ActivPanel.ir
Add "Settings" button to Promethean ActivPanel. Found from the remote that is linked to the ActivPanel at my school.
> Add "Settings" button to Promethean ActivPanel

- Blu-Ray/Samsung/Samsung_B59-01301A.ir
> Create Samsung_B59-01301A.ir #509

- ACs/Eurom/Eurom PAC 9.2.ir
- ACs/Eurom/Eurom_PAC_9.2.ir
Tested on the Eurom PAC 9.2 in my room <3
> Add Eurom PAC9.2 Remote

- ACs/SoleusAir/SoleusAir Portable.ir
- ACs/SoleusAir/SoleusAir_Portable.ir
Added IR for the SolusAir Portable Air Conditioning series.
> Add SolusAir Portable.ir

- Touchscreen_Displays/Onescreen/Onescreen.ir
Added IR remote for onescreen touchscreen display device.
> Added onescreen remote

- Cameras/Sony/Sony_RMT_831.ir
Remote Control for DCR Series and Other Camcorders Handycams
> Added Sony RMT-831 for 00's Camcorders

- TVs/Samsung/Samsung_Service_Menu.ir
FACTORY and 3SPEED buttons unlocks hidden properties in service menu
> Samsung FACTORY and 3SPEED buttons

- TVs/TCL/TCL_43S446.ir
> Added new TCL remote

- Speakers/Microlab/Microlab_SOLO11.ir
> add Microlab_SOLO11.ir

- TVs/Dynex/Dynex_RC-701-0A.ir
Add Dynex_RC-701-0A -remote
for TV DX-24L150A11 Rev.A
> Add Dynex_RC-701-0A

- Miscellaneous/Avfabul/avstar_hdmi_splitter_switch.ir
Adds the AVfabul-AVstar HDMI switch/splitter
> Add AVfabul-AVstar HDMI switch/splitter

- Computer/Apple/Apple_Remote_Gen2.ir
- Computers/Apple/Apple_Remote_Gen2.ir
This remote is different from the Apple TV remote.
I create new folder Computers and subfolder Apple.
For the record, PN is A1294.
> adding Apple Remote Gen2 (https://en.wikipedia.org/wiki/Apple_Remote)

- Digital_Signs/LG/LG_AKB74915384.ir
Recorded the buttons from this remote today because I didn't see it in here yet.
> Add LG AKB74915384 remote

- CD_Players/Onkyo/Onkyo_DX-7333.ir
- CD_Players/Onkyo/Onkyo_RC-402C_for_Onkyo Compact Disk Player DX-7333.ir
Onkyo RC-402C Remote for **Onkyo Compact Disk Player DX-7333**
> Added Onkyo DX-7333

- Heaters/Dr_Heater/Dr_heater_infrared.ir
- Speakers/Teufel/Teufel_CEM500RC.ir
Dr. Heater infrared heater remote control and
Teufel CEM 500 RC for Teufel Concept E Magnum Power Edition added
> multipe files added

- Audio_Receivers/Sony/Sony_TA-F261R.ir
This PR adds new codes for the audio receiver Sony TA-F261R.
> Add codes for audio receiver Sony TA-F261R.

- ACs/Zephir/Zephir_ZPO9001H_AC.ir
Added Zephir brand to ACs and added ZPO9001H portable AC remote
> Added Zephir brand and ZPO9001H AC remote

- Projectors/JVC/JVC_LX-UH1B.ir
added JVC in projectors and added JVC LX-UH1B remote
> Add JVC LX-UH1B Projector

- Speakers/DollarTec_BT5AmpBoard/DollarTec_BT5AmpBoard.ir
Add support for the DollarTec Bluetooth 5.0 Amplifier Board
> New device: DollarTec Bluetooth 5.0 Amplifier Board

- Audio_Receivers/Douk_Audio/Douk_ST-01_Pro.ir
Adding Douk_Audio/Douk_ST-01_Pro.ir
> Adding Douk_Audio/Douk_ST-01_Pro.ir

- Consoles/Philips/CDi_Commander.ir
Adding Philips/CDi_Commander.ir
> Adding Philips/CDi_Commander.ir

- Converters/Retro-Bit/Retro-Bit_Prism.ir
Adding Retro-Bit/Retro-Bit_Prism.ir
> Adding Retro-Bit/Retro-Bit_Prism.ir

- Converters/OSSC/OSSC_Pro.ir
This adds captures for the OSSC Pro remote, documented at https://junkerhq.net/xrgb/index.php?title=OSSC_Pro
> Add OSSC Pro remote

- SoundBars/DutchOriginals/dutch_originals_soundbar.ir
Reverse engineered remote protocol for the Dutch Originals sound bar.
> Add Dutch Originals Soundbar

- Blu-Ray/LG/LG_AKB73495301.ir
- Cable_Boxes/Xfinity/Xfinity_XR15_V2-UQ.ir
- TVs/Samsung/Samsung_BN59-01315J.ir
- Added LG AKB73495301 Blu-Ray disc player remote
- Added Xfinity XR15 v2-UQ cable box remote
- Added Samsung BN59-01315J TV remote
> Added recent contributions in March

- LED_Lighting/ONN-Lighting/ONN.ir
- LED_Lighting/ONN-Lighting/ONN_LED.ir
Added folder and .ir file for ONN 32' and 16' LED strip remote.
> ONN 32' and 16' LED strips

- Touchscreen_Displays/SMART_Technologies/SMART_Board_MX.ir
I made a issue on this a while ago, and now I got my hands on a remote and updated it.
> Add Left button to SMART Board remote

- Multimedia/MT-VIKI/MT-VIKI-MT-HD0808.ir
Add MT-VIKI MTHD0808 HDMI 4K 8x8 Matrix Switcher
> Add MT-VIKI MTHD0808 HDMI 4K 8x8 Matrix Switcher

- Car_Multimedia/DVD_Players/Lexus/Lexus_LX570_2018_MultimediaRearEntertainmentSystem
- Car_Multimedia/DVD_Players/Lexus/Lexus_LX570_2018_Rear_Media.ir
for lexus lx570 2018 rear entertainment system
> Added Lexus_LX570_2018_MultimediaRearEntertainmentSystem

- Projectors/Groview/Groview.ir
- Projectors/Groview/readme.md
This projector came with a remote that I've seen across other projectors, most of them cheap ones on amazon.
Groview 1080p projector (No model)
https://www.amazon.com/gp/product/B0BY23QDV5
> Added a Groview projector with a generic remote

- Audio_and_Video_Receivers/Rio/Rio_Sonic_Blue_059PXC.ir
Created Rio folder in Audio_and_Video_Receivers and added IR file Rio_Sonic_Blue_059PXC.ir
> Created Rio folder and added Rio Sonic Blue IR file

- SoundBars/LG/LG_AKB74815321.ir
Apologies, I have never contributed to a GitHub before, I hope this is correct.
I added underscores to the names of the commands, which makes some of them look a little odd on the Flipper, not sure if this is right?
> Added LG Soundbar Remote AKB74815321 .ir File

- DVD_Players/Sony/Sony_J-6090-203-A.ir
Sony Service Remote file from official flipper forum.
> Sony Service Remote Controller J-6090-203-A

- TVs/BGH/BGH_BLE2814D.ir
Hi, how are you?
So I clone this remote that I found. I could not clone all the buttons because they didn't work :)
> feat(TVs): Add new brand and tv model

- TVs/Strong/Strong_TVD221_B1825.ir
(small remote of e.g. SRT 40FD5553 LED-TV)
> Add Strong TVD211 B1825 Remote

- Cable_Boxes/Eurolan/Eurolan_TH100.ir
Eurolan TH100
Spec: https://www.eurolan.net/en/th100.html
PDF: http://www.eurolan.net/datasheets/TH100.pdf (contains an image and a description of the remote)
Buttons have been recorded left->right from top row down
> Eurolan TH100

- TVs/LG/LG_AKB75095307.ir
Mute and Info cannot have the same code (A:0x04 C:0x09)
> LG_AKB75095307 bugfix

- .fff-ir-lint.json
- Humidifiers/Maxcan/Maxcan_mh_602brc.ir
- README.md
* Added LED Naming Rewrites (https://github.com/logickworkshop/Flipper-IRDB/pull/603)
* Added Maxcan 602brc (https://github.com/logickworkshop/Flipper-IRDB/pull/604)
* Added Documentation for LED Naming Scheme (https://github.com/logickworkshop/Flipper-IRDB/pull/605)
> Pull changes from logickworkshop/Flipper-IRDB

- .github/workflows/pr-lint.yaml
* updated actions
* create a comment (only in `Lucaslhm/Flipper-IRDB`; does not work in forks) with linter result
> ci: add linter comment on pull request

- TVs/Panasonic/N2QAYB001109.ir
- TVs/Panasonic/N2QAYB001109_full.ir
Short and full version included
> Add Panasonic N2QAYB 001109

- TVs/Samsung/Samsung_LN32D403E2GCTC.ir
I think that works exactly as the LN46, jeje
> feat(TVs): Add new model

- Miscellaneous/MonoPrice/MonoPrice-HDMI-Switch.ir
> added MonoPrice Blackbird HDMI Switcher remote

- Miscellaneous/LightMyBricks/lightmybricks.ir
This PR adds support for the [LightMyBricks remote control](https://www.lightmybricks.com/products/remote-control-and-sound-kit) that controls their sound kit and lights.
> Added support for LightMyBricks remote

- Audio_and_Video_Receivers/NAD/NAD_DR2_D3020V1.ir
Hi !
I have done the fuzzing and testing to reverse engineer a remote for the audio amplifier NAD D3020. 
Can i contribute to the IRDB ? 
Best Regards, 
Nicolas
> Add IR file for NAD DR2 3020 7050

- CD_Players/Panasonic/Panasonic_RXDS750.ir
Picked up this 3 disc stereo system and was lucky enough for it to come with a remote
> Add the panasonic rx-ds750 remote

- Fireplaces/ModernEmber/ModernEmber_Fireplace.ir
Captured from the included OEM remote. https://www.electricfireplacesdirect.com/products/modern-ember-60-in-aerus-smart-linear-electric-fireplace
> Added Modern Ember fireplace remote

- LED_Lighting/Luminara/Luminara_Candle.ir
The previous file only had power on/off. This update adds support for flicker (on/off), brightness (up/down), and timers.
Pulled from a Luminara remote.
> Updated Luminara Candle

- TVs/Onn/Onn_Roku_TV.ir
Updated Onn Roku TV to include all Channels and use standard names. Added sleep.
> Updated Onn Roku TV

- ACs/DeLonghi/Pinguino_PAC_EL92_SILENT.ir
- Miscellaneous/Coretec/TRAINER_1000.ir
Pinguino_PAC_EL92_SILENT added
> added new Pinguino AC

- TVs/Panasonic/Panasonic_TX29AS10C.ir
> add Panasonic_TX29AS10C

- SoundBars/Grundig/Grundig_DSB_950.ir
https://www.grundig.com/de-de/produkte/lautsprecher/lautsprecher-dsb-950-black
> Add Grundig DSB 950 Soundbar

- Speakers/Ruark/Ruark_MR1.ir
> Add Ruark MR1 remote

- LED_Lighting/Deluxe_Homeart/Deluxe_Homeart_FB-00001.ir
Add Deluxe Homeart FB-00001
https://www.deluxehomeart.com/catalog/item/FB-00001
> feat: create Deluxe Homeart FB-00001

- Fans/KOENIC/KOENIC_KTFC_602722.ir
Add IR File for KOENIC KTFC 602722 Cooling Tower Fan.
> Add KOENIC KTFC 602722 cooling fan IR file

- Audio_and_Video_Receivers/Harman_Kardon/Harman Kardon_bds580.ir
Added IR codes for Harman Kardon BDS580. Tested on device, all working.
> Create Harman Kardon_bds580.ir

- Air_Purifiers/Trotec/Trotec_AirgoClean_350_E.ir
Adding the Remote for AirgoClean 350 E Remote
> Add Trotec AirgoClean 350 E Remote

- SoundBars/Denon/Denon_DHT_S216.ir
This adds the Denon DHT-S216 Sound Bar.
> Add Denon DHT-S216

- LICENSE
- README.md
This Pull Request adds the CC0-1.0 Universal License to Flipper-IRDB. Note that there is a placeholder `(HEAD^^)` in the README. This will be updated in another PR when this PR was merged.
> [!NOTE]
> @/maintainers: After this PR was merged, **we should NOT merge any other Pull Requests until the PR authors explicitly accept the new license.**
@amec0e I cannot assign you as reviewer, please also approve/deny this PR :)
related: #959 #843 
(I am leaving this PR open after the other maintainers approved it for another week if anyone wants to discuss the change.)
> feat: add LICENSE and add license note to README
